### ISSUE TITLE
Languages added in private groups are leaking into the public group

### ISSUE THREAD

**Issue by MartinPaulEve** [birkbeckOLH/annotran#79]

**Comment by mari-ja** [comment]
In writing to db everything looks ok.
Possible bug could be in languages.js where languages are ordered per groups.

**Comment by MartinPaulEve** [comment]
Bug is in annotran/languages/models.py in get_public function.

Bug occurs when:

1. Language has been added to public group on _another/different page_.
2. Language is added to a private group on the page in question.

Bug occurs because:

1. Query filters by language_id=X and group_id=-1 in group_language table (true and records returned because it has been added to a different page)
2. Query then filters by language_id=X and page_id=Y (true because the language is on the page in a group)

**Comment by MartinPaulEve** [comment]
Suggested fix:

1. Add GROUP_ID column to LANGUAGE_PAGE table

**Comment by mari-ja** [comment]
This was a bigger issue as translations (languages listed in a drop-down box) were not unique for all: page, group and language. Needed changes have been introduced.
