### ISSUE TITLE
translation replacement

### ISSUE THREAD

**Issue by mari-ja** [birkbeckOLH/annotran#9]
User should be able to replace text on the page with all translations for a particular author and a particular language. To get all replacements done, the author and the language are selected within the sidebar. Partial replacements should be provided per each translation, so allowing mixing replacements from different authors. To get this implemented, use js module implemented as a part of #2 issue.

**Comment by MartinPaulEve** [comment]
Fixed in 08f4d0b240156a9b60c977b8060afe51ec627ea3
